ARG RUNTIME_IMAGE
FROM ${RUNTIME_IMAGE}

ARG RELEASE_VERSION
ARG SOURCE_FINGERPRINT
LABEL org.opencontainers.image.title="WB Tender release" \
      org.opencontainers.image.version="${RELEASE_VERSION}" \
      org.opencontainers.image.revision="${SOURCE_FINGERPRINT}"

ENV EXTERNAL_SUBMISSION_ENABLED=false \
    WB_TENDER_ALLOW_EXTERNAL_SUBMISSION=false \
    WB_TENDER_SAAS_ENABLED=false \
    WB_TENDER_SAAS_LEGACY_API_ENABLED=false

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --omit=dev
COPY --chown=root:root . /app/
COPY --chown=root:root deployment/wb-tender-ingestion-entrypoint /usr/local/bin/wb-tender-ingestion-entrypoint
RUN chmod 0555 /usr/local/bin/wb-tender-ingestion-entrypoint
