import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { createServer } from "node:http";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { chromium } from "playwright";

const browserPath=process.env.CHROMIUM_EXECUTABLE_PATH||chromium.executablePath(),browserAvailable=existsSync(browserPath);
const ui=readFileSync(new URL("../platform/assets/autopilot-navigation.js",import.meta.url)),pdfJs=readFileSync(new URL("../node_modules/pdfjs-dist/build/pdf.min.mjs",import.meta.url)),pdfWorker=readFileSync(new URL("../node_modules/pdfjs-dist/build/pdf.worker.min.mjs",import.meta.url));
const tender="11111111-1111-4111-8111-111111111111",company="22222222-2222-4222-8222-222222222222",required="33333333-3333-4333-8333-333333333333";
const workingCopy="44444444-4444-4444-8444-444444444444",sourceDocument="55555555-5555-4555-8555-555555555555",workingSha="a".repeat(64),sourceSha="b".repeat(64);

test("normal 96-page PDF supports page-83 overlays, save, reload and rendered download",{skip:!browserAvailable},async(t)=>{
  const fixture=await PDFDocument.create(),font=await fixture.embedFont(StandardFonts.Helvetica);for(let page=1;page<=96;page++){const sheet=fixture.addPage([600,800]);sheet.drawText(`Rendered source page ${page}`,{x:72,y:720,size:24,font,color:rgb(0,0,0)})}const pdf=Buffer.from(await fixture.save());
  const mutations=[];let version=1,overlays=[],satisfaction="MISSING";
  const server=createServer(async(req,res)=>{
    if(req.method==="GET"&&req.url.startsWith("/admin/ausschreibungen/autopilot/management-output")){res.setHeader("content-type","text/html");res.setHeader("set-cookie","wb_csrf=journey-token; Path=/; SameSite=Strict");return res.end('<!doctype html><body data-base="/admin/ausschreibungen" data-api="/api/tender"><nav id="autopilot-nav"></nav><section id="autopilot-content"></section><script src="/autopilot-navigation.js"></script></body>')}
    if(req.url==="/autopilot-navigation.js"){res.setHeader("content-type","application/javascript; charset=utf-8");return res.end(ui)}
    if(req.url==="/admin/ausschreibungen/pdfjs/pdf.mjs"){res.setHeader("content-type","application/javascript");return res.end(pdfJs)}
    if(req.url==="/admin/ausschreibungen/pdfjs/pdf.worker.mjs"){res.setHeader("content-type","application/javascript");return res.end(pdfWorker)}
    if(req.method==="GET"&&req.url.startsWith("/api/tender/final-preflight/contexts"))return json(res,{items:[{tender_id:tender,company_id:company,lot_key:"LOT-1",calculation_id:null,readiness_status:"OPEN",requirements:[]}]});
    if(req.method==="GET"&&req.url.startsWith(`/api/tender/tenders/${tender}/management-output`)){res.statusCode=404;return json(res,{error:"not_found"})}
    if(req.method==="GET"&&req.url.startsWith(`/api/tender/tenders/${tender}/required-documents?`)){const review=satisfaction==="MANUAL_REVIEW_REQUIRED",validated=satisfaction==="VALIDATED";return json(res,{summary:{missing:review||validated?0:1,blockers:validated?0:1,manualReview:review?1:0,validated:validated?1:0},items:[{id:required,requirement_title:"Normales PDF",requirement_description:"Synthetische Browser-Fixture",source_reference:"Testquelle",source_page:83,mandatory:true,submission_relevant:true,requirement_classification:"FILLABLE_BIDDER_FORM",classification_reason:"Synthetisches ausfüllbares Bieterformular.",action_type:"PDF_EDITOR",satisfaction_status:satisfaction,status_label:review?"Dokument gespeichert – bereit zur fachlichen Prüfung":validated?"Dokument fachlich bestätigt":"Einzureichendes Dokument fehlt",accepted_formats:["application/pdf"],working_copy_id:version>1?workingCopy:null,working_copy_version:version>1?version:null,working_copy_sha256:version>1?workingSha:null,working_source_document_id:version>1?sourceDocument:null,working_source_sha256:version>1?sourceSha:null,source_document:{available:true,documentId:sourceDocument,sha256:sourceSha,filename:"96-seiten.pdf",documentVersion:1,mimeType:"application/pdf",page:83},original_form:{status:"NO_PROVEN_MAPPING",downloadable:false,editable:false,filename:null,mimeType:null}}]})}
    if(req.method==="POST"&&req.url.endsWith(`/${required}/working-copy`)){mutations.push(await request(req));return json(res,{item:{id:`copy-${version}`,version},idempotent:version>1,transmitted:false},version>1?200:201)}
    if(req.method==="GET"&&req.url.includes(`/${required}/working-copy/fields?`))return json(res,{item:{id:`copy-${version}`,version,filename:"Arbeitskopie-96-seiten.pdf",sha256:"a".repeat(64),sourceSha256:"b".repeat(64),signatureFieldCount:0,fields:[],overlays,pageCount:96,suggestedPage:83},overlayEditable:true,acroFormEditable:false,originalUnchanged:true,transmitted:false});
    if(req.method==="POST"&&req.url.endsWith(`/${required}/working-copy/overlays`)){const mutation=await request(req);mutations.push(mutation);overlays=mutation.body.elements;version++;satisfaction="MANUAL_REVIEW_REQUIRED";return json(res,{item:{id:`copy-${version}`,version},elementCount:overlays.length,materiallyEdited:true,status:satisfaction,statusLabel:"Dokument gespeichert – bereit zur fachlichen Prüfung",originalUnchanged:true,signatureAdded:false,externalWrite:false,transmitted:false},201)}
    if(req.method==="POST"&&req.url.endsWith(`/${required}/review`)){const mutation=await request(req);mutations.push(mutation);satisfaction="VALIDATED";return json(res,{status:"VALIDATED",statusLabel:"Dokument fachlich bestätigt",transmitted:false})}
    if(req.method==="GET"&&req.url.includes(`/${required}/working-copy?`)){res.setHeader("content-type","application/pdf");return res.end(pdf)}
    res.statusCode=404;json(res,{error:"fixture_not_found",url:req.url});
  });
  await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));t.after(()=>server.close());
  const browser=await chromium.launch({headless:true,executablePath:browserPath});t.after(()=>browser.close());const page=await browser.newPage(),pageErrors=[];page.on("pageerror",error=>pageErrors.push(error.stack||error.message));
  const origin=`http://127.0.0.1:${server.address().port}`;await page.goto(`${origin}/admin/ausschreibungen/autopilot/management-output?tender=${tender}&company=${company}&lot=LOT-1`,{waitUntil:"networkidle"});
  let edit=page.getByRole("button",{name:"PDF am Bildschirm ausfüllen"});await edit.waitFor({timeout:5000}).catch(async error=>{throw new Error(`${await page.content()}\n${pageErrors.join(" | ")}\n${error.message}`)});await edit.click();
  await page.getByText("Seite 83 von 96",{exact:true}).waitFor({timeout:20000}).catch(async error=>{throw new Error(`${await page.locator("[data-page-status]").textContent()} | ${pageErrors.join(" | ")} | ${error.message}`)});assert.equal(await page.locator("[data-page-number]").inputValue(),"83");
  const renderedPixels=await page.locator("[data-pdf-canvas]").evaluate(canvas=>{const pixels=canvas.getContext("2d").getImageData(0,0,canvas.width,canvas.height).data;let nonblank=0;for(let i=0;i<pixels.length;i+=4)if(pixels[i+3]>0&&pixels[i]+pixels[i+1]+pixels[i+2]<700)nonblank++;return nonblank});assert.ok(renderedPixels>100,"PDF page contains visible nonblank rendered pixels");
  await page.getByRole("button",{name:"Textfeld"}).click();await page.locator("[data-overlay-text]").fill("SYNTHETIC BROWSER VALUE");await page.locator("[data-overlay-width]").fill("17.3");await page.locator("[data-overlay-height]").fill("2.7");await page.locator("[data-overlay-font-size]").fill("0.9");const textOverlay=page.locator(".pdf-overlay-text"),before=await textOverlay.getAttribute("style");await textOverlay.focus();await textOverlay.press("ArrowRight");await textOverlay.press("ArrowDown");const moved=await textOverlay.getAttribute("style");assert.notEqual(moved,before);
  await page.getByRole("button",{name:"X",exact:true}).click();await page.getByRole("button",{name:"Als neue Working-Copy-Version speichern"}).click();await page.getByText("Version 2 mit 2 Overlay-Elementen gespeichert",{exact:false}).waitFor();
  assert.equal(mutations.length,2);assert.deepEqual(mutations[0].body,{company,lot:"LOT-1"});assert.equal(mutations[0].csrf,"journey-token");assert.equal(mutations[1].body.baseVersion,1);assert.equal(mutations[1].body.elements.length,2);assert.ok(mutations[1].body.elements.every(element=>element.page===83));const savedText=mutations[1].body.elements.find(element=>element.type==="text");assert.equal(savedText.text,"SYNTHETIC BROWSER VALUE");assert.ok(Math.abs(savedText.width-.173)<1e-9);assert.ok(Math.abs(savedText.height-.027)<1e-9);assert.ok(Math.abs(savedText.fontSize-.009)<1e-9);assert.equal(mutations[1].csrf,"journey-token");
  await page.getByRole("button",{name:"Editor schließen"}).click();await page.getByText("Dokument gespeichert – bereit zur fachlichen Prüfung",{exact:true}).waitFor();assert.equal(await page.getByText(/davon 0 fehlend und 1 zur Prüfung/).count(),1);edit=page.getByRole("button",{name:"PDF am Bildschirm ausfüllen"});await edit.click();await page.getByText("Seite 83 von 96",{exact:true}).waitFor({timeout:10000});assert.equal(await page.locator(".pdf-overlay-element").count(),2);assert.equal(await page.locator(".pdf-overlay-text").getAttribute("style"),moved);await page.locator(".pdf-overlay-text").click();assert.equal(await page.locator("[data-overlay-width]").inputValue(),"17.3");assert.equal(await page.locator("[data-overlay-font-size]").inputValue(),"0.9");assert.match(await page.locator("[data-working-copy-download]").getAttribute("href"),/working-copy\?company=.*lot=LOT-1/);assert.equal(await page.locator("[data-pdf-version]").textContent(),"2");
  const downloaded=await page.locator("[data-working-copy-download]").evaluate(async link=>{const response=await fetch(link.href,{credentials:"same-origin",cache:"no-store"}),bytes=new Uint8Array(await response.arrayBuffer());return {status:response.status,mime:response.headers.get("content-type"),magic:String.fromCharCode(...bytes.slice(0,5)),size:bytes.length}});assert.equal(downloaded.status,200);assert.match(downloaded.mime,/application\/pdf/);assert.equal(downloaded.magic,"%PDF-");assert.ok(downloaded.size>1000);
  await page.getByRole("button",{name:"Editor schließen"}).click();page.once("dialog",dialog=>dialog.accept("Synthetic human review note"));await page.getByRole("button",{name:"Als passend bestätigen"}).click();await page.getByText(/0 Unterlagen offen/).waitFor();const reviewMutation=mutations.at(-1);assert.equal(reviewMutation.csrf,"journey-token");assert.deepEqual(reviewMutation.body,{company,lot:"LOT-1",decision:"VALIDATED",reason:"Synthetic human review note",target:{type:"WORKING_COPY",id:workingCopy,version:2,sha256:workingSha,sourceDocumentId:sourceDocument,sourceSha256:sourceSha}});assert.equal(await page.getByRole("button",{name:"Als passend bestätigen"}).count(),0);
  assert.deepEqual(pageErrors,[]);
});

test("each fillable card opens its own exact source page while upload-only and contract clauses have no editor",{skip:!browserAvailable},async(t)=>{
  const fixture=await PDFDocument.create(),font=await fixture.embedFont(StandardFonts.Helvetica);for(let n=1;n<=70;n++){const sheet=fixture.addPage([600,800]);sheet.drawText(`Exact physical page ${n}`,{x:72,y:720,size:24,font})}const pdf=Buffer.from(await fixture.save());
  const fill52="66666666-6666-4666-8666-666666666652",fill12="66666666-6666-4666-8666-666666666612",upload68="66666666-6666-4666-8666-666666666668",clause48="66666666-6666-4666-8666-666666666648";
  const source=(page)=>({available:true,documentId:sourceDocument,sha256:sourceSha,filename:"source.pdf",documentVersion:1,mimeType:"application/pdf",page});
  const original={status:"NO_PROVEN_MAPPING",downloadable:false,editable:false,filename:null,mimeType:null};
  const items=[
    {id:fill52,requirement_title:"Formular Seite 52",requirement_description:"Vom Bieter auszufüllen",source_reference:"source.pdf",source_page:52,mandatory:true,submission_relevant:true,requirement_classification:"FILLABLE_BIDDER_FORM",classification_reason:"Eindeutige Formularfelder.",action_type:"PDF_EDITOR",satisfaction_status:"MISSING",status_label:"Einzureichendes Dokument fehlt",accepted_formats:["application/pdf"],source_document:source(52),original_form:original},
    {id:fill12,requirement_title:"Formular Seite 12",requirement_description:"Vom Bieter auszufüllen",source_reference:"source.pdf",source_page:12,mandatory:true,submission_relevant:true,requirement_classification:"FILLABLE_BIDDER_FORM",classification_reason:"Eindeutige Formularfelder.",action_type:"PDF_EDITOR",satisfaction_status:"MISSING",status_label:"Einzureichendes Dokument fehlt",accepted_formats:["application/pdf"],source_document:source(12),original_form:original},
    {id:upload68,requirement_title:"Bid-time Nachweis Seite 68",requirement_description:"Mit dem Angebot einzureichen",source_reference:"source.pdf",source_page:68,mandatory:true,submission_relevant:true,requirement_classification:"BID_TIME_UPLOAD_EVIDENCE",classification_reason:"Explizit mit dem Angebot.",action_type:"UPLOAD",satisfaction_status:"MISSING",status_label:"Einzureichendes Dokument fehlt",accepted_formats:["application/pdf"],source_document:source(68),original_form:original},
    {id:clause48,requirement_title:"Vertragsklausel Seite 48",requirement_description:"Nach Zuschlag vorzulegen",source_reference:"source.pdf",source_page:48,mandatory:false,submission_relevant:false,requirement_classification:"POST_AWARD_EVIDENCE",classification_reason:"Erst nach Zuschlag.",action_type:"NONE",satisfaction_status:"NOT_REQUIRED",status_label:"Nicht erforderlich",accepted_formats:["application/pdf"],source_document:source(48),original_form:original},
  ];
  const relevanceMutations=[];let manuallyExcluded=null;
  const server=createServer(async(req,res)=>{
    if(req.method==="GET"&&req.url.startsWith("/admin/ausschreibungen/autopilot/management-output")){res.setHeader("content-type","text/html");res.setHeader("set-cookie","wb_csrf=journey-token; Path=/; SameSite=Strict");return res.end('<!doctype html><body data-base="/admin/ausschreibungen" data-api="/api/tender"><nav id="autopilot-nav"></nav><section id="autopilot-content"></section><script src="/autopilot-navigation.js"></script></body>')}
    if(req.url==="/autopilot-navigation.js"){res.setHeader("content-type","application/javascript; charset=utf-8");return res.end(ui)}
    if(req.url==="/admin/ausschreibungen/pdfjs/pdf.mjs"){res.setHeader("content-type","application/javascript");return res.end(pdfJs)}
    if(req.url==="/admin/ausschreibungen/pdfjs/pdf.worker.mjs"){res.setHeader("content-type","application/javascript");return res.end(pdfWorker)}
    if(req.method==="GET"&&req.url.startsWith("/api/tender/final-preflight/contexts"))return json(res,{items:[{tender_id:tender,company_id:company,lot_key:"LOT-1",calculation_id:null,readiness_status:"OPEN",requirements:[]}]});
    if(req.method==="GET"&&req.url.startsWith(`/api/tender/tenders/${tender}/management-output`)){res.statusCode=404;return json(res,{error:"not_found"})}
    if(req.method==="GET"&&req.url.startsWith(`/api/tender/tenders/${tender}/required-documents?`))return json(res,{summary:{missing:manuallyExcluded?2:3,blockers:manuallyExcluded?2:3,manualReview:0,validated:0},items:items.map(item=>item.id===fill52?{...item,manual_submission_relevance_override:manuallyExcluded===true?false:null,status_label:manuallyExcluded?"Manuell als für die Angebotsabgabe nicht erforderlich bestätigt":item.status_label}:item)});
    if(req.method==="POST"&&req.url.endsWith(`/${fill52}/submission-relevance`)){const mutation=await request(req);relevanceMutations.push(mutation);manuallyExcluded=mutation.body.decision==="NOT_REQUIRED";return json(res,{requiredDocumentId:fill52,decision:mutation.body.decision,changed:true,bidSubmissionRelevanceState:manuallyExcluded?"MANUALLY_NOT_REQUIRED":"REQUIRED",status:"MISSING",statusLabel:manuallyExcluded?"Manuell als für die Angebotsabgabe nicht erforderlich bestätigt":"Einzureichendes Dokument fehlt",transmitted:false})}
    const selected=[fill52,fill12].find(id=>req.url.includes(`/${id}/working-copy`));
    if(selected&&req.method==="POST"&&req.url.endsWith("/working-copy")){await request(req);return json(res,{item:{id:`copy-${selected}`,version:1},transmitted:false},201)}
    if(selected&&req.method==="GET"&&req.url.includes("/working-copy/fields?")){const pageNumber=selected===fill52?52:12;return json(res,{item:{id:`copy-${selected}`,version:1,filename:"working.pdf",sha256:workingSha,sourceSha256:sourceSha,fields:[],overlays:[],pageCount:70,suggestedPage:pageNumber},overlayEditable:true,transmitted:false})}
    if(selected&&req.method==="GET"&&req.url.includes("/working-copy?")){res.setHeader("content-type","application/pdf");return res.end(pdf)}
    res.statusCode=404;return json(res,{error:"fixture_not_found",url:req.url});
  });
  await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));t.after(()=>server.close());
  const browser=await chromium.launch({headless:true,executablePath:browserPath});t.after(()=>browser.close());const page=await browser.newPage(),pageErrors=[];page.on("pageerror",error=>pageErrors.push(error.stack||error.message));
  await page.goto(`http://127.0.0.1:${server.address().port}/admin/ausschreibungen/autopilot/management-output?tender=${tender}&company=${company}&lot=LOT-1`,{waitUntil:"networkidle"});
  assert.equal(await page.locator(`[data-required-document="${clause48}"] [data-pdf-edit]`).count(),0);
  assert.equal(await page.locator(`[data-required-document="${clause48}"] [data-required-upload]`).count(),0);
  assert.equal(await page.locator(`[data-required-document="${upload68}"] [data-pdf-edit]`).count(),0);
  assert.equal(await page.locator(`[data-required-document="${upload68}"] [data-required-upload]`).count(),1);
  assert.equal(await page.locator("[data-required-relevance]").count(),3,"every active required-document card has the relevance action");assert.equal(await page.locator(`[data-required-document="${clause48}"] [data-required-relevance]`).count(),0,"auto inactive clauses cannot be reactivated");
  await page.locator(`[data-required-document="${fill52}"] [data-required-relevance]`).click();const relevanceDialog=page.locator("#wb-required-relevance-dialog");await relevanceDialog.waitFor();assert.equal(await relevanceDialog.getByText("Ist dieser Nachweis für die Angebotsabgabe erforderlich?",{exact:true}).count(),1);assert.deepEqual(await relevanceDialog.locator("[data-relevance-answer], [data-relevance-cancel]").allTextContents(),["Ja","Nein","Abbrechen"]);await relevanceDialog.getByRole("button",{name:"Abbrechen"}).click();assert.equal(relevanceMutations.length,0,"Abbrechen sends no request");
  await page.locator(`[data-required-document="${fill52}"] [data-required-relevance]`).click();await page.locator("#wb-required-relevance-dialog").getByRole("button",{name:"Nein"}).click();await page.getByText("Manuell als für die Angebotsabgabe nicht erforderlich bestätigt.",{exact:true}).waitFor();assert.equal(relevanceMutations.length,1);assert.deepEqual(relevanceMutations[0].body,{company,lot:"LOT-1",decision:"NOT_REQUIRED"});assert.equal(relevanceMutations[0].csrf,"journey-token");
  await page.locator(`[data-required-document="${fill52}"] [data-required-relevance]`).click();await page.locator("#wb-required-relevance-dialog").getByRole("button",{name:"Ja"}).click();await page.getByText("Der Nachweis bleibt für die Angebotsabgabe erforderlich.",{exact:true}).waitFor();assert.equal(relevanceMutations.length,2);assert.equal(relevanceMutations[1].body.decision,"REQUIRED");
  await page.locator(`[data-required-document="${fill52}"] [data-pdf-edit]`).click();await page.getByText("Seite 52 von 70",{exact:true}).waitFor({timeout:20000}).catch(async error=>{throw new Error(`${await page.locator("[data-page-status]").textContent()} | ${pageErrors.join(" | ")} | ${error.message}`)});assert.equal(await page.locator("[data-page-number]").inputValue(),"52");
  await page.getByRole("button",{name:"Editor schließen"}).click();
  await page.locator(`[data-required-document="${fill12}"] [data-pdf-edit]`).click();await page.getByText("Seite 12 von 70",{exact:true}).waitFor({timeout:10000});assert.equal(await page.locator("[data-page-number]").inputValue(),"12");
});

const json=(res,value,status=200)=>{res.statusCode=status;res.setHeader("content-type","application/json");res.end(JSON.stringify(value))};
const request=async req=>{let raw="";for await(const chunk of req)raw+=chunk;return {body:JSON.parse(raw),csrf:req.headers["x-csrf-token"]}};
