import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import test from "node:test";
import {CANONICAL_SERVICES,STRUCTURED_REGION_SCHEMA,canonicalService,evaluateStructuredRegions,giscoNutsForPoint,regionChecksum,validateStructuredRegionConfiguration} from "../platform/structured-regions.mjs";

const routes=readFileSync(new URL("../platform/autopilot-routes.mjs",import.meta.url),"utf8"),configuration=readFileSync(new URL("../platform/configuration-admin.mjs",import.meta.url),"utf8"),ui=readFileSync(new URL("../platform/assets/configuration.js",import.meta.url),"utf8"),inboxUi=readFileSync(new URL("../platform/assets/inbox-regions.js",import.meta.url),"utf8"),migration=readFileSync(new URL("../migrations/095_structured_core_regions.sql",import.meta.url),"utf8"),atomicMigration=readFileSync(new URL("../migrations/099_atomic_structured_region_approval.sql",import.meta.url),"utf8"),pipeline=readFileSync(new URL("../platform/inbox-pipeline.mjs",import.meta.url),"utf8");
const state={nuts:"DE1",iso:"DE-BW",label:"Baden-Württemberg"};
const uniqueGeocode=async()=>[{postalCode:"76131",state,latitude:49.0094,longitude:8.4044,localities:["Karlsruhe"],displayName:"Karlsruhe, 76131, Deutschland",reference:"R62578",licence:"OSM ODbL"}];
const nutsLookup=async code=>code==="DE122"?{code,name:"Karlsruhe",provider:"EUROSTAT_GISCO_NUTS_2024"}:null;
const nutsForPoint=async()=>({code:"DE122",name:"Karlsruhe, Stadtkreis",hierarchy:["DE1","DE12","DE122"],provider:"EUROSTAT_GISCO_NUTS_2024",referenceUrl:"https://gisco.example/NUTS3.geojson",referenceScale:"01M",referenceCrs:"EPSG:4326"});
const validate=value=>validateStructuredRegionConfiguration(value,{geocode:uniqueGeocode,nutsLookup,nutsForPoint,now:()=>new Date("2026-08-19T00:00:00Z")});

test("all and only productive canonical services are supported",()=>{
  assert.deepEqual(CANONICAL_SERVICES,["security","cleaning","facility_management","sicherheitstechnik","emergency_services"]);
  assert.equal(canonicalService("facility-management"),"facility_management");assert.equal(canonicalService("emergency-services"),"emergency_services");assert.equal(canonicalService("invented-service"),null);
});
test("place and exact postcode resolve uniquely without invented values",async()=>{const result=await validate({regions:[{type:"PLACE_RADIUS",place:"Karlsruhe",postalCode:"76131",radiusKm:25}]});assert.equal(result.valid,true);assert.equal(result.configuration.regions[0].place,"Karlsruhe");assert.equal(result.configuration.regions[0].postalCode,"76131");assert.equal(result.configuration.regions[0].nutsCode,"DE122");assert.deepEqual(result.configuration.regions[0].nutsHierarchy,["DE1","DE12","DE122"]);assert.equal(result.configuration.regions[0].evidence.reference,"R62578")});
test("same-name place without a unique postcode cannot be activated",async()=>{const result=await validateStructuredRegionConfiguration({regions:[{type:"PLACE_RADIUS",place:"Neustadt",postalCode:"12345",radiusKm:20}]},{geocode:async()=>[{postalCode:"12345",state,latitude:49,longitude:8,localities:["Neustadt"]},{postalCode:"12345",state,latitude:50,longitude:9,localities:["Neustadt"]}],nutsLookup,nutsForPoint});assert.equal(result.valid,false);assert.equal(result.configuration.regions[0].validationCode,"place_postal_ambiguous")});
test("Augsburg postcode and coordinates retain the official finest NUTS hierarchy",async()=>{const bavaria={nuts:"DE2",iso:"DE-BY",label:"Bayern"},result=await validateStructuredRegionConfiguration({schema:STRUCTURED_REGION_SCHEMA,regions:[{id:"augsburg",type:"PLACE_RADIUS",place:"Augsburg",postalCode:"86150",state:"Bayern",radiusKm:150}]},{geocode:async()=>[{postalCode:"86150",state:bavaria,latitude:48.3644523,longitude:10.8928079,localities:["Augsburg"],displayName:"Augsburg, Bayern, Deutschland",reference:"R62407",licence:"OSM ODbL"}],nutsLookup,nutsForPoint:async()=>({code:"DE271",name:"Augsburg, Kreisfreie Stadt",hierarchy:["DE2","DE27","DE271"],provider:"EUROSTAT_GISCO_NUTS_2024",referenceUrl:"https://gisco.example/NUTS3.geojson",referenceScale:"01M",referenceCrs:"EPSG:4326"}),now:()=>new Date("2026-08-19T00:00:00Z")});assert.equal(result.valid,true);assert.equal(result.configuration.regions[0].nutsCode,"DE271");assert.deepEqual(result.configuration.regions[0].nutsHierarchy,["DE2","DE27","DE271"]);assert.equal(result.configuration.regions[0].radiusKm,150)});
test("place activation fails closed when official NUTS-3 precision is unavailable",async()=>{const result=await validateStructuredRegionConfiguration({regions:[{type:"PLACE_RADIUS",place:"Karlsruhe",postalCode:"76131",radiusKm:25}]},{geocode:uniqueGeocode,nutsLookup,nutsForPoint:async()=>null});assert.equal(result.valid,false);assert.equal(result.configuration.regions[0].validationCode,"nuts_precision_unresolved");assert.equal(result.configuration.regions[0].nutsCode,null)});
test("missing postcode stays invalid",async()=>{const result=await validate({regions:[{type:"PLACE_RADIUS",place:"Karlsruhe",radiusKm:25}]});assert.equal(result.valid,false);assert.equal(result.configuration.regions[0].postalCode,null)});
test("radius classifies supplied performance coordinates inside and outside",async()=>{const valid=(await validate({regions:[{type:"PLACE_RADIUS",place:"Karlsruhe",postalCode:"76131",radiusKm:20}]})).configuration;assert.equal(evaluateStructuredRegions(valid,[{latitude:49.01,longitude:8.41,locality:"Karlsruhe",postalCode:"76131"}]).classification,"CORE_REGION");assert.equal(evaluateStructuredRegions(valid,[{latitude:50.11,longitude:8.68,locality:"Frankfurt",postalCode:"60311"}]).classification,"OUTSIDE_CORE_REGION")});
test("PLACE_RADIUS never promotes an entire shared NUTS area",async()=>{const valid=(await validate({regions:[{type:"PLACE_RADIUS",place:"Karlsruhe",postalCode:"76131",radiusKm:20}]})).configuration;assert.equal(evaluateStructuredRegions(valid,[{latitude:50.11,longitude:8.68,nuts:"DE122"}]).classification,"OUTSIDE_CORE_REGION")});
test("radius without evidenced performance coordinates is unresolved",async()=>{const valid=(await validate({regions:[{type:"PLACE_RADIUS",place:"Karlsruhe",postalCode:"76131",radiusKm:20}]})).configuration;assert.equal(evaluateStructuredRegions(valid,[{locality:"Karlsruhe",postalCode:"76131"}]).classification,"REGION_UNRESOLVED")});
test("NUTS and state rules are canonical and matching",async()=>{const nuts=(await validate({regions:[{type:"NUTS",nutsCode:"DE122"}]})).configuration,stateRule=(await validate({regions:[{type:"STATE",state:"Baden-Württemberg"}]})).configuration;assert.equal(evaluateStructuredRegions(nuts,[{nuts:"DE122"}]).classification,"CORE_REGION");assert.equal(evaluateStructuredRegions(stateRule,[{nuts:"DE146"}]).classification,"CORE_REGION")});
test("unknown syntactically plausible NUTS code is rejected by official lookup",async()=>{const result=await validate({regions:[{type:"NUTS",nutsCode:"DE199"}]});assert.equal(result.valid,false);assert.equal(result.configuration.regions[0].validationCode,"nuts_unresolved")});
test("missing and multiple performance locations never become core",async()=>{const valid=(await validate({regions:[{type:"POSTAL_CODE",postalCode:"76131"}]})).configuration;assert.equal(evaluateStructuredRegions(valid,[]).classification,"REGION_UNRESOLVED");assert.equal(evaluateStructuredRegions(valid,[{postalCode:"76131"},{postalCode:"76133"}]).classification,"MULTI_REGION_REVIEW")});
test("contracting authority location is not used as performance location",async()=>{const valid=(await validate({regions:[{type:"POSTAL_CODE",postalCode:"76131"}]})).configuration;assert.equal(evaluateStructuredRegions(valid,[]).classification,"REGION_UNRESOLVED");assert.doesNotMatch(pipeline,/buyer.*locations|locations.*buyer/i)});
test("company, service, profile, tenant and active version are constrained in SQL",()=>{for(const token of ["scope.tenant_id","scope.company_id","scope.canonical_service","scope.profile_id","scope.active_region_version_id","active_configuration_version_id"])assert.match(routes,new RegExp(token.replace(".","\\.")));assert.match(configuration,/v\.tenant_id=\$1 AND v\.company_id=\$2 AND v\.canonical_service=\$3 AND v\.profile_id=\$4/)});
test("version history endpoint requires exact company and service context",()=>{assert.match(configuration,/configuration_scope_required/);assert.match(migration,/configuration_versions_exact_history_idx/);assert.match(ui,/configurationScopeQuery/)});
test("Security and Cleaning cannot share profile or version queries",()=>{assert.match(configuration,/configuration_scopes WHERE company_id=\$1 AND canonical_service=\$2/);assert.match(configuration,/scope\.profile_id/);assert.match(routes,/company_service_mismatch/)});
test("core region filter maps only to CORE_REGION",()=>{assert.match(routes,/regionFilter === "default"[\s\S]*?\["CORE_REGION", "STRATEGIC_REGION"\]/);assert.match(routes,/regionFilter[\s\S]*?\.split\(","\)/);assert.doesNotMatch(inboxUi,/<option value="CORE_REGION">[^<]*Strateg/)});
test("rapid filter changes abort old requests and discard stale responses",()=>{assert.match(inboxUi,/inboxRequestController\?\.abort\(\)/);assert.match(inboxUi,/requestSequence!==inboxRequestSequence/);assert.match(inboxUi,/AbortError/)});
test("structured UI has repeatable rows, all fields, validation and removal",()=>{for(const token of ["data-add-region","data-remove-region","PLACE_RADIUS","POSTAL_CODE","NUTS","STATE","postalCode","radiusKm","validationStatus"])assert.match(ui,new RegExp(token));assert.match(ui,/Vorschau vor Aktivierung/)});
test("RLS and tenant isolation are declared for structured region tables",()=>{assert.match(migration,/ENABLE ROW LEVEL SECURITY/g);assert.match(migration,/configuration_tenant_isolation/g);assert.match(migration,/current_setting\('app\.configuration_tenant_id',true\)/)});
test("one active structured profile is enforced per exact tenant scope",()=>{assert.match(atomicMigration,/CREATE UNIQUE INDEX IF NOT EXISTS region_profile_versions_one_active_scope_idx/);assert.match(atomicMigration,/WHERE status='ACTIVE'/);assert.match(atomicMigration,/HAVING count\(\*\)>1/)});
test("atomic activation uses explicit SQL types and a locked active-version token",()=>{assert.match(configuration,/\(\$1::uuid\)::text/);assert.match(configuration,/FOR UPDATE OF scope/);assert.match(configuration,/expectedActiveRegionVersionId/);assert.match(configuration,/approved\.rowCount!==1/);assert.match(configuration,/INSERT INTO tender\.configuration_audit[\s\S]*?COMMIT/)});
test("volatile validation timestamps do not break idempotent region checksums",()=>{const one={schema:STRUCTURED_REGION_SCHEMA,regions:[{id:"fixed",type:"STATE",nutsCode:"DE2",evidence:{validatedAt:"2026-08-19T01:00:00Z"}}]},two={schema:STRUCTURED_REGION_SCHEMA,regions:[{id:"fixed",type:"STATE",nutsCode:"DE2",evidence:{validatedAt:"2026-08-19T02:00:00Z"}}]};assert.equal(regionChecksum(one),regionChecksum(two))});
test("configuration validation and persistence are idempotent",async()=>{const one=await validate({schema:STRUCTURED_REGION_SCHEMA,regions:[{id:"fixed",type:"STATE",state:"Bayern"}]}),two=await validate({schema:STRUCTURED_REGION_SCHEMA,regions:[{id:"fixed",type:"STATE",state:"Bayern"}]});assert.equal(regionChecksum(one.configuration),regionChecksum(two.configuration));assert.match(migration,/ON CONFLICT\(company_id,canonical_service\) DO NOTHING/);assert.match(pipeline,/ON CONFLICT\(event_fingerprint\) DO NOTHING/)});
