import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {approvedDispatchBinding,assertFrozenDispatch,assertDispatchDocuments,bytesHash,dispatchScopeKey,dispatchFailure,verifyDispatchReceipt} from '../platform/submission-dispatch-core.mjs';
import {liveSubmissionHash} from '../platform/submission-live-core.mjs';
const uid=()=>crypto.randomUUID(),hash=bytesHash(Buffer.from('fixture'));
function fixture(){const buffer=Buffer.from('Non-binding test offer'),document={id:uid(),filename:'offer.pdf',sizeBytes:buffer.length,sha256:bytesHash(buffer),version:1};const binding=approvedDispatchBinding({origin:'TENANT_PORTAL',tenantId:uid(),companyId:uid(),tenderId:uid(),portalId:uid(),sourceId:uid(),releasedBy:uid(),calculationId:uid(),lotKey:'LOT-1',portalTenderReference:'NON-BINDING-1',portalHost:'sandbox.invalid',portalTenderUrl:'https://sandbox.invalid/tender/1',portalAdapterId:'fixture',portalAdapterVersion:'1',calculationVersion:1,packageVersion:1,packageSha256:hash,calculationSha256:hash,sourceSha256:hash,deadlineAt:new Date(Date.now()+3600000).toISOString(),releasedAt:new Date(Date.now()-1000).toISOString(),documents:[document]});const row={binding,binding_sha256:liveSubmissionHash(binding),scope_key:dispatchScopeKey(binding)};for(const [column,key] of [['tenant_id','tenantId'],['company_id','companyId'],['tender_id','tenderId'],['portal_id','portalId'],['lot_key','lotKey'],['released_by','releasedBy'],['package_sha256','packageSha256']])row[column]=binding[key];return {binding,row,documents:[{...document,buffer}]};}
test('approved binding and exact document bytes validate',()=>{const f=fixture();assert.equal(assertFrozenDispatch(f.row),f.binding);assert.equal(assertDispatchDocuments(f.binding,f.documents),true)});
test('no dispatch without immutable management approval',()=>{const f=fixture();f.row.binding={...f.binding,releaseStatus:'READY_FOR_MANAGEMENT'};assert.throws(()=>assertFrozenDispatch(f.row),/management_approval_required/)});
for(const [column,value]of [['tenant_id',uid()],['company_id',uid()],['lot_key','LOT-2'],['tender_id',uid()],['portal_id',uid()]])test('reject changed '+column,()=>{const f=fixture();f.row[column]=value;assert.throws(()=>assertFrozenDispatch(f.row),/scope_changed/)});
test('different package or portal cannot evade duplicate scope',()=>{const f=fixture();assert.equal(dispatchScopeKey(f.binding),dispatchScopeKey({...f.binding,packageSha256:'b'.repeat(64),portalId:uid(),sourceId:uid()}));assert.notEqual(dispatchScopeKey(f.binding),dispatchScopeKey({...f.binding,lotKey:'LOT-2'}))});
test('document version and bytes are frozen',()=>{const f=fixture();assert.throws(()=>assertDispatchDocuments(f.binding,[{...f.documents[0],version:2}]),/bytes_changed/);assert.throws(()=>assertDispatchDocuments(f.binding,[{...f.documents[0],buffer:Buffer.from('replaced')}]),/bytes_changed/)});
test('missing and duplicate documents rejected',()=>{const f=fixture();assert.throws(()=>assertDispatchDocuments(f.binding,[]));assert.throws(()=>assertDispatchDocuments(f.binding,[...f.documents,...f.documents]))});
test('past deadline cannot be approved',()=>{const f=fixture();assert.throws(()=>approvedDispatchBinding({...f.binding,deadlineAt:new Date(Date.now()-1).toISOString()}),/deadline_expired/)});
test('network interruption before finalization has bounded retry',()=>{const f=fixture();assert.equal(dispatchFailure({code:'submission_network_unavailable'},{deadlineAt:f.binding.deadlineAt,attempt:1}).status,'RETRY_REQUIRED');assert.equal(dispatchFailure({code:'submission_network_unavailable'},{deadlineAt:f.binding.deadlineAt,attempt:4}).retry,false)});
test('uncertain finalization never retries even after restart',()=>{const f=fixture();const r=dispatchFailure({code:'submission_network_unavailable'},{deadlineAt:f.binding.deadlineAt,attempt:1,commitStarted:true});assert.equal(r.status,'MANUAL_INTERVENTION_REQUIRED');assert.equal(r.retry,false);assert.equal(r.reconcile,true)});
for(const [code,state]of [['submission_credentials_required','CREDENTIALS_REQUIRED'],['submission_portal_changed','PORTAL_CHANGED'],['submission_deadline_expired','DEADLINE_EXPIRED']])test(code,()=>{assert.equal(dispatchFailure({code},{deadlineAt:fixture().binding.deadlineAt}).status,state)});
test('exception messages containing secrets never become persisted errors',()=>{assert.equal(dispatchFailure(new Error('secret-should-not-be-persisted'),{deadlineAt:fixture().binding.deadlineAt}).code,'submission_operation_failed')});
test('only actual receipt with matching manifest and scope accepted',()=>{const f=fixture();const receipt={verified:true,reference:'SANDBOX-RECEIPT',portalHost:f.binding.portalHost,tenderReference:f.binding.portalTenderReference,lotKey:f.binding.lotKey,packageSha256:f.binding.packageSha256,submittedAt:new Date().toISOString(),documents:f.binding.documents,bytes:Buffer.from('test receipt')};assert.equal(verifyDispatchReceipt(f.binding,receipt).sha256,bytesHash(receipt.bytes));assert.throws(()=>verifyDispatchReceipt(f.binding,{...receipt,lotKey:'wrong'}));assert.throws(()=>verifyDispatchReceipt(f.binding,{...receipt,documents:[]}));assert.throws(()=>verifyDispatchReceipt(f.binding,{...receipt,submittedAt:new Date(Date.now()+600000).toISOString()}));assert.throws(()=>verifyDispatchReceipt(f.binding,{...receipt,verified:false}))});

test('native and legacy representations of one legal company share a duplicate scope',()=>{const f=fixture();assert.equal(dispatchScopeKey({...f.binding,companyId:uid(),canonicalCompanyId:f.binding.companyId}),dispatchScopeKey(f.binding))});
