import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './submission-dispatch-fixture.mjs';
import {executeDispatch} from '../platform/submission-dispatch-worker.mjs';
import {dispatchFailure,verifyDispatchReceipt} from '../platform/submission-dispatch-core.mjs';
function scenario({fault,changedSource=false}={}){
 const f=fixture(),events=[];f.row.id='dispatch';f.row.status='SUBMISSION_QUEUED';f.row.deadline_at=f.binding.deadlineAt;
 const claim={db:{},row:f.row,async fence({allowCommitted=false}={}){if(this.row.commit_started_at&&!allowCommitted)throw new Error('commit replay');},async heartbeat(){events.push('heartbeat')},async submitting(){this.row.status='SUBMITTING';events.push('SUBMITTING')},async evidence(name){events.push(name)},async commitIntent(validate){await validate();events.push('DURABLE_COMMIT_INTENT');this.row.commit_started_at=new Date()},async complete(receipt){verifyDispatchReceipt(this.row.binding,receipt);events.push('RECEIPT_PERSISTED');return{status:'SUBMITTED'}},async fail(error){events.push('FAILED');return dispatchFailure(error,{deadlineAt:this.row.deadline_at,commitStarted:Boolean(this.row.commit_started_at),attempt:1})},async close(){events.push('LOCK_RELEASED')}};
 const {releasedBy,releasedAt,releaseStatus,schemaVersion,...binding}=f.binding;
 let sourceCalls=0;
 const options={source:async()=>{sourceCalls++;return{binding:changedSource&&sourceCalls>1?{...binding,companyProfileId:'changed'}:binding,documents:f.documents}},credentials:async()=>{if(fault==='credentials')throw new Error('submission_credentials_required');return{secret:{username:'fixture',password:'fixture'},credentialId:'credential',revision:1}},operationalGate:async()=>{if(fault==='gate')throw new Error('submission_gate_disabled');return 'fixed-profile'},adapterFactory:async()=>({async prepare({onEvidence}){if(fault==='portal')throw new Error('submission_portal_changed');if(fault==='network-before')throw Object.assign(new Error('network'),{code:'submission_network_unavailable'});await onEvidence('UPLOAD_VERIFIED',{})},async submit({beforeCommit,fence}){await beforeCommit();await fence();events.push('PORTAL_FINALIZE');if(fault==='network-after')throw new Error('timeout');return{verified:true,reference:'NON_BINDING_RECEIPT',submittedAt:new Date().toISOString(),portalHost:f.binding.portalHost,tenderReference:f.binding.portalTenderReference,lotKey:f.binding.lotKey,packageSha256:f.binding.packageSha256,documents:f.binding.documents,bytes:Buffer.from('receipt')}},async close(){events.push('BROWSER_CLOSED')}})};
 return {claim,options,events};
}
test('approval job executes exact version and persists intent before portal finalization and receipt before unlocking',async()=>{const s=scenario();assert.equal((await executeDispatch(s.claim,s.options)).status,'SUBMITTED');const e=s.events;assert.ok(e.indexOf('DURABLE_COMMIT_INTENT')<e.indexOf('PORTAL_FINALIZE'));assert.ok(e.indexOf('PORTAL_FINALIZE')<e.indexOf('RECEIPT_PERSISTED'));assert.ok(e.indexOf('RECEIPT_PERSISTED')<e.indexOf('LOCK_RELEASED'))});
test('unapproved job never opens portal',async()=>{const s=scenario();s.claim.row.binding={...s.claim.row.binding,releaseStatus:'DRAFT'};const r=await executeDispatch(s.claim,s.options);assert.notEqual(r.status,'SUBMITTED');assert.ok(!s.events.includes('SUBMITTING'));assert.ok(!s.events.includes('PORTAL_FINALIZE'))});
for(const [fault,state] of [['credentials','CREDENTIALS_REQUIRED'],['portal','PORTAL_CHANGED'],['network-before','RETRY_REQUIRED'],['gate','MANUAL_INTERVENTION_REQUIRED']])test(fault+' before finalization is safe',async()=>{const s=scenario({fault});const r=await executeDispatch(s.claim,s.options);assert.equal(r.status,state);assert.ok(!s.events.includes('PORTAL_FINALIZE'));assert.equal(s.events.at(-1),'LOCK_RELEASED')});
test('source changes between upload and finalization prevent transmission',async()=>{const s=scenario({changedSource:true});const r=await executeDispatch(s.claim,s.options);assert.equal(r.status,'MANUAL_INTERVENTION_REQUIRED');assert.ok(!s.events.includes('DURABLE_COMMIT_INTENT'));assert.ok(!s.events.includes('PORTAL_FINALIZE'))});
test('network loss after final request closes browser and requires reconciliation',async()=>{const s=scenario({fault:'network-after'});const r=await executeDispatch(s.claim,s.options);assert.equal(r.status,'MANUAL_INTERVENTION_REQUIRED');assert.equal(r.retry,false);assert.equal(s.events.filter(e=>e==='PORTAL_FINALIZE').length,1);assert.ok(!s.events.includes('RECEIPT_PERSISTED'));assert.ok(s.events.indexOf('BROWSER_CLOSED')<s.events.indexOf('LOCK_RELEASED'))});

test('lost response may reconcile a real receipt without repeating finalization',async()=>{const s=scenario({fault:'network-after'});const factory=s.options.adapterFactory;s.options.adapterFactory=async()=>({...await factory(),async reconcileCurrentPage(){const b=s.claim.row.binding;return{verified:true,reference:'READ-ONLY-RECEIPT',submittedAt:new Date().toISOString(),portalHost:b.portalHost,tenderReference:b.portalTenderReference,lotKey:b.lotKey,packageSha256:b.packageSha256,documents:b.documents,bytes:Buffer.from('actual fixture receipt')}}});assert.equal((await executeDispatch(s.claim,s.options)).status,'SUBMITTED');assert.equal(s.events.filter(e=>e==='PORTAL_FINALIZE').length,1)});
