import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './submission-dispatch-fixture.mjs';
import {BrowserSubmissionAdapter,submissionRequestAllowed,validateSubmissionProfile} from '../platform/submission-browser-adapter.mjs';
import {verifyDispatchReceipt} from '../platform/submission-dispatch-core.mjs';
process.env.NODE_ENV='test';
function profile(b){return{kind:'WB_BROWSER_SUBMISSION_PROFILE_V1',host:b.portalHost,adapterId:b.portalAdapterId,adapterVersion:b.portalAdapterVersion,existingReceiptSelector:'#reference',target:{tender:{selector:'#tender'},lot:{selector:'#lot'}},upload:{inputSelector:'#upload',rowsSelector:'.uploaded',filenameSelector:'.name',downloadSelector:'a'},submit:{selector:'#submit',text:'Nicht bindendes Testangebot abgeben'},receipt:{reference:{selector:'#reference'},timestamp:{selector:'#timestamp'},tender:{selector:'#receipt-tender'},lot:{selector:'#receipt-lot'}},requests:[{phase:'UPLOAD',method:'POST',path:'/upload'},{phase:'COMMIT',method:'POST',path:'/submit'}]};}
test('finalization request cannot escape phase or portal boundary',()=>{const {binding:b}=fixture(),p=profile(b);assert.equal(submissionRequestAllowed({url:'https://'+b.portalHost+'/submit',method:'POST'},{binding:b,profile:p,phase:'UPLOAD'}),false);assert.equal(submissionRequestAllowed({url:'https://foreign.invalid/submit',method:'POST'},{binding:b,profile:p,phase:'COMMIT'}),false);assert.equal(submissionRequestAllowed({url:'https://'+b.portalHost+'/submit',method:'POST'},{binding:b,profile:p,phase:'COMMIT'}),true)});
test('overlapping form actions require disjoint action values',()=>{const {binding:b}=fixture(),p=profile(b);p.requests=[{phase:'UPLOAD',method:'POST',path:'/action',formField:'action',formValue:'send'},{phase:'COMMIT',method:'POST',path:'/action',formField:'action',formValue:'send'}];assert.throws(()=>validateSubmissionProfile(p,b,{isolatedTest:true}),/portal_changed/)});
for(const changedLot of [false,true])test('isolated Chromium upload and receipt, wrong lot='+changedLot,async()=>{
 const {binding:b,documents}=fixture(),p=profile(b),uploaded=new Map();let finalizations=0,intent=false;
 const adapter=new BrowserSubmissionAdapter({binding:b,profile:p,portal:{},isolatedTest:true,authenticate:async()=>({resultCode:'LOGIN_ERFOLGREICH',documentAccess:true,session:{storageState:{cookies:[],origins:[]},sessionStorage:[]}}),setupContext:async context=>{
  await context.route('**/*',async route=>{const request=route.request(),url=new URL(request.url());
   if(url.pathname==='/upload'){assert.equal(request.method(),'POST');const body=request.postDataBuffer();assert.ok(body.includes(documents[0].buffer));uploaded.set(documents[0].filename,documents[0].buffer);return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({filename:documents[0].filename})})}
   if(url.pathname==='/submit'){assert.equal(intent,true);assert.equal(uploaded.size,1);finalizations++;return route.fulfill({status:200,contentType:'text/html',body:`<span id="reference">NON-BINDING-RECEIPT</span><span id="timestamp">${new Date().toISOString()}</span><span id="receipt-tender">${b.portalTenderReference}</span><span id="receipt-lot">${b.lotKey}</span>`})}
   return route.fulfill({status:200,contentType:'text/html',body:`<!doctype html><span id="tender">${b.portalTenderReference}</span><span id="lot">${changedLot?'WRONG-LOT':b.lotKey}</span><input id="upload" type="file"><section id="files"></section><button id="submit">Nicht bindendes Testangebot abgeben</button><script>document.querySelector('#upload').onchange=async e=>{const data=new FormData();data.append('file',e.target.files[0]);const r=await fetch('/upload',{method:'POST',body:data});const d=await r.json();const row=document.createElement('div');row.className='uploaded';const name=document.createElement('span');name.className='name';name.textContent=d.filename;const link=document.createElement('a');link.href='/download/'+encodeURIComponent(d.filename);link.textContent='Download';row.append(name,link);document.querySelector('#files').append(row)};document.querySelector('#submit').onclick=async()=>{const r=await fetch('/submit',{method:'POST',body:'nonbinding=true'});document.body.innerHTML=await r.text()};</script>`});
  });
 }});
 // Test-only download provider reads bytes uploaded through the real browser form.
 adapter.download=async url=>{const name=decodeURIComponent(new URL(url).pathname.split('/').at(-1));assert.ok(uploaded.has(name));return uploaded.get(name)};
 try{
  if(changedLot){await assert.rejects(adapter.prepare({credential:{username:'test-account',password:'test-password'},documents,fence:async()=>{}}),/portal_binding_invalid/);assert.equal(finalizations,0);assert.equal(uploaded.size,0)}
  else{await adapter.prepare({credential:{username:'test-account',password:'test-password'},documents,fence:async()=>{}});assert.equal(finalizations,0);const result=await adapter.submit({beforeCommit:async()=>{intent=true},fence:async()=>{assert.equal(intent,true)}});assert.equal(finalizations,1);assert.equal(verifyDispatchReceipt(b,result).reference,'NON-BINDING-RECEIPT')}
 }finally{await adapter.close()}
});
