import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import test from "node:test";
import {activateStructuredRegions} from "../platform/configuration-admin.mjs";
import {STRUCTURED_REGION_SCHEMA,regionChecksum} from "../platform/structured-regions.mjs";

const tenant="11111111-1111-4111-8111-111111111111",company="22222222-2222-4222-8222-222222222222",profile="33333333-3333-4333-8333-333333333333",configurationId="44444444-4444-4444-8444-444444444444",activeRegion="55555555-5555-4555-8555-555555555555",actor="66666666-6666-4666-8666-666666666666";
const region={schema:STRUCTURED_REGION_SCHEMA,regions:[{id:"augsburg",type:"PLACE_RADIUS",place:"Augsburg",postalCode:"86150",state:"Bayern",radiusKm:150,nutsCode:"DE271",nutsHierarchy:["DE2","DE27","DE271"],latitude:48.3644523,longitude:10.8928079,validationStatus:"VALID",validationCode:"PLACE_POSTAL_NUTS3_UNIQUE",evidence:{provider:"NOMINATIM_OSM",nutsProvider:"EUROSTAT_GISCO_NUTS_2024"}}]};
const version={id:configurationId,tenant_id:tenant,company_id:company,canonical_service:"security",profile_id:profile,service_line:"security",version_no:133,impact_preview:{regionPreview:{tenantId:tenant,companyId:company,canonicalService:"security",profileId:profile,configurationChecksum:regionChecksum(region),previousActiveRegionVersionId:activeRegion}}};
const changes=[{parameter_key:"A08",new_value:region}];

function fakeClient({activeRows=[{id:activeRegion}],failAt=""}={}){
  const queries=[];
  return {queries,async query(sql,params=[]){queries.push({sql,params});if(failAt&&sql.includes(failAt))throw Object.assign(new Error("synthetic_sql_failure"),{code:"XX999"});if(sql.includes("UPDATE tender.region_profile_versions"))return {rows:activeRows,rowCount:activeRows.length};if(sql.includes("INSERT INTO tender.region_profile_versions"))return {rows:[{id:"77777777-7777-4777-8777-777777777777",status:"ACTIVE"}],rowCount:1};if(sql.includes("UPDATE tender.configuration_scopes"))return {rows:[],rowCount:1};return {rows:[],rowCount:1}}};
}

test("valid structured activation supersedes once, inserts one immutable active version, rules, scope and job",async()=>{const client=fakeClient(),created=await activateStructuredRegions(client,version,changes,actor);assert.equal(created.status,"ACTIVE");assert.equal(client.queries.filter(q=>q.sql.includes("UPDATE tender.region_profile_versions")).length,1);assert.equal(client.queries.filter(q=>q.sql.includes("INSERT INTO tender.region_profile_versions")).length,1);assert.equal(client.queries.filter(q=>q.sql.includes("INSERT INTO tender.region_profile_rules")).length,1);assert.equal(client.queries.filter(q=>q.sql.includes("INSERT INTO tender.region_recalculation_jobs")).length,1)});
test("recalculation SQL explicitly separates UUID and text parameter typing",async()=>{const client=fakeClient();await activateStructuredRegions(client,version,changes,actor);const job=client.queries.find(q=>q.sql.includes("region_recalculation_jobs"));assert.match(job.sql,/\$1::uuid/);assert.match(job.sql,/\(\$1::uuid\)::text/);assert.match(job.sql,/\(\$6::uuid\)::text/);assert.doesNotMatch(job.sql,/concat\([^)]*\$1[^:]/)});
test("more than one prior active region version fails closed",async()=>{const client=fakeClient({activeRows:[{id:activeRegion},{id:"88888888-8888-4888-8888-888888888888"}]});await assert.rejects(()=>activateStructuredRegions(client,version,changes,actor),error=>error.safeCode==="multiple_active_region_versions");assert.equal(client.queries.some(q=>q.sql.includes("INSERT INTO tender.region_profile_versions")),false)});
test("a SQL failure is propagated for the owning transaction to roll back",async()=>{const client=fakeClient({failAt:"region_recalculation_jobs"});await assert.rejects(()=>activateStructuredRegions(client,version,changes,actor),error=>error.code==="XX999");assert.equal(client.queries.at(-1).sql.includes("region_recalculation_jobs"),true)});
test("invalid structured rows cannot be activated",async()=>{const client=fakeClient(),invalid=structuredClone(changes);invalid[0].new_value.regions[0].validationStatus="INVALID";await assert.rejects(()=>activateStructuredRegions(client,version,invalid,actor),/structured_region_validation_required/);assert.equal(client.queries.length,0)});
test("stale preview checksum cannot activate",async()=>{const client=fakeClient(),stale=structuredClone(version);stale.impact_preview.regionPreview.configurationChecksum="0".repeat(64);await assert.rejects(()=>activateStructuredRegions(client,stale,changes,actor),/structured_region_preview_required/);assert.equal(client.queries.length,0)});

const backend=readFileSync(new URL("../platform/configuration-admin.mjs",import.meta.url),"utf8"),frontend=readFileSync(new URL("../platform/assets/configuration.js",import.meta.url),"utf8"),worker=readFileSync(new URL("../platform/region-recalculation-worker.mjs",import.meta.url),"utf8"),pipeline=readFileSync(new URL("../platform/inbox-pipeline.mjs",import.meta.url),"utf8"),migration=readFileSync(new URL("../migrations/099_atomic_structured_region_approval.sql",import.meta.url),"utf8");
test("board route locks draft and exact scope before comparing active version",()=>{assert.match(backend,/SELECT \* FROM tender\.configuration_versions WHERE id=\$1 FOR UPDATE/);assert.match(backend,/FOR UPDATE OF scope/);assert.match(backend,/expectedActiveRegionVersionId/)});
test("board route writes audits before commit and rolls back every caught error",()=>{const board=backend.slice(backend.indexOf('app.post("/api/configuration/versions/:id/self-approve-activate"'));assert.match(board,/INSERT INTO tender\.configuration_audit[\s\S]*?COMMIT/);assert.match(board,/catch\(e\)[\s\S]*?ROLLBACK/);assert.match(board,/Entwurf blieb unverändert\. Fehlerkennung/)});
test("frontend performs preview then sends locked active region version",()=>{assert.match(frontend,/preview\.regionPreview\?\.previousActiveRegionVersionId\|\|"none"/);assert.match(frontend,/expectedActiveRegionVersionId:button\.dataset\.expectedActiveRegionVersion/);assert.match(frontend,/Vorschau geprüft – jetzt aktivieren/)});
test("board permission is initialized before the first form render",()=>{const catalogStart=frontend.indexOf('get("/configuration/catalog").then(d=>{canSelfApproveActivate='),firstRender=frontend.indexOf('render("profiles")',catalogStart);assert.ok(catalogStart>=0);assert.ok(firstRender>catalogStart);assert.equal((frontend.match(/canSelfApproveActivate=d\.currentUser/g)||[]).length,1)});
test("scope worker only selects relevant tenders for the activated company and service",()=>{assert.match(worker,/relevance\.company_id=\$1/);assert.match(worker,/\)\=\$2/);assert.match(worker,/scope:\{tenantId:job\.tenant_id,companyId:job\.company_id,canonicalService:job\.canonical_service,profileId:job\.profile_id\}/)});
test("regionalization preserves workflow decisions and avoids duplicate inbox events",()=>{assert.match(pipeline,/prior\?\.workflow_status\|\|"NEW"/);assert.match(pipeline,/prior\?\.responsible_user_id\|\|null/);assert.match(pipeline,/ON CONFLICT\(event_fingerprint\) DO NOTHING/)});
test("database enforces exactly one active region version per exact scope",()=>{assert.match(migration,/tenant_id,company_id,canonical_service,profile_id/);assert.match(migration,/WHERE status='ACTIVE'/);assert.match(migration,/multiple_active_region_profile_versions/)});
