BEGIN;
ALTER TABLE tender.autopilot_queue DROP CONSTRAINT IF EXISTS autopilot_queue_action_type_check;
ALTER TABLE tender.autopilot_queue ADD CONSTRAINT autopilot_queue_action_type_check CHECK(action_type=ANY(ARRAY[
  'TEST_PORTAL_CONNECTION','TEST_DOCUMENT_FETCH','RESOLVE_TARGET_PORTAL','VALIDATE_PORTAL_ADAPTER',
  'FETCH_DOCUMENTS','ANALYZE_DOCUMENTS','REFRESH_ENRICHMENT','VALIDATE_CALCULATION_INPUTS',
  'START_CALCULATION','REFRESH_REVIEW','GENERATE_RECOMMENDATION','RUN_FULL_PIPELINE',
  'GENERATE_BOARD_REPORT','EXPORT_REVIEW_REPORT','EXPORT_BOARD_BRIEF','START_PORTAL_AUTHENTICATION'
]::text[]));
INSERT INTO tender.audit_events(action,metadata) VALUES('PORTAL_AUTHENTICATION_QUEUE_ACTION_ENABLED',jsonb_build_object('release','20260821-portal-regions-completion.27','dataChanged',false,'externalWrite',false));
COMMIT;
