BEGIN;
DROP VIEW IF EXISTS tender.current_scoped_region_evaluations;
DROP POLICY IF EXISTS configuration_tenant_isolation ON tender.configuration_versions;
DROP POLICY IF EXISTS configuration_tenant_isolation ON tender.region_evaluations;
DROP POLICY IF EXISTS configuration_tenant_isolation ON tender.management_inbox;
ALTER TABLE tender.configuration_versions DISABLE ROW LEVEL SECURITY;
ALTER TABLE tender.region_evaluations DISABLE ROW LEVEL SECURITY;
ALTER TABLE tender.management_inbox DISABLE ROW LEVEL SECURITY;
ALTER TABLE tender.region_evaluations DROP COLUMN IF EXISTS region_profile_version_id;
ALTER TABLE tender.region_evaluations DROP COLUMN IF EXISTS profile_id;
ALTER TABLE tender.region_evaluations DROP COLUMN IF EXISTS canonical_service;
ALTER TABLE tender.region_evaluations DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE tender.management_inbox DROP COLUMN IF EXISTS region_profile_version_id;
ALTER TABLE tender.management_inbox DROP COLUMN IF EXISTS profile_id;
ALTER TABLE tender.management_inbox DROP COLUMN IF EXISTS canonical_service;
ALTER TABLE tender.management_inbox DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE tender.configuration_scopes DROP CONSTRAINT IF EXISTS configuration_scopes_active_region_fk;
DROP TABLE IF EXISTS tender.region_profile_rules;
DROP TABLE IF EXISTS tender.region_profile_versions;
ALTER TABLE tender.configuration_versions DROP CONSTRAINT IF EXISTS configuration_versions_exact_scope_fk;
ALTER TABLE tender.configuration_versions DROP COLUMN IF EXISTS profile_id;
ALTER TABLE tender.configuration_versions DROP COLUMN IF EXISTS canonical_service;
ALTER TABLE tender.configuration_versions DROP COLUMN IF EXISTS tenant_id;
DROP TABLE IF EXISTS tender.configuration_scopes;
DROP TABLE IF EXISTS tender.configuration_tenants;
COMMIT;
