const STATE_CODES=Object.freeze({
 "baden-württemberg":"DE1","baden-wuerttemberg":"DE1",bayern:"DE2",berlin:"DE3",brandenburg:"DE4",bremen:"DE5",hamburg:"DE6",hessen:"DE7","mecklenburg-vorpommern":"DE8",niedersachsen:"DE9","nordrhein-westfalen":"DEA","rheinland-pfalz":"DEB",saarland:"DEC",sachsen:"DED","sachsen-anhalt":"DEE","schleswig-holstein":"DEF",thüringen:"DEG",thueringen:"DEG",
});
const STATE_LABELS=Object.freeze({DE1:"Baden-Württemberg",DE2:"Bayern",DE3:"Berlin",DE4:"Brandenburg",DE5:"Bremen",DE6:"Hamburg",DE7:"Hessen",DE8:"Mecklenburg-Vorpommern",DE9:"Niedersachsen",DEA:"Nordrhein-Westfalen",DEB:"Rheinland-Pfalz",DEC:"Saarland",DED:"Sachsen",DEE:"Sachsen-Anhalt",DEF:"Schleswig-Holstein",DEG:"Thüringen"});
export const REGION_LABELS=Object.freeze({CORE_REGION:"Kernregion",STRATEGIC_REGION:"Strategische/bedingte Region",OUTSIDE_CORE_REGION:"Außerhalb der Kernregion",EXCLUDED_REGION:"Ausgeschlossene Region",REGION_UNRESOLVED:"Region nicht eindeutig ermittelbar",REGION_CONFIG_CONFLICT:"Widersprüchliche Regionskonfiguration",MULTI_REGION_REVIEW:"Mehrere Regionen – Einzelprüfung erforderlich",NOT_APPLICABLE:"Nicht anwendbar"});

const norm=value=>String(value??"").normalize("NFKC").trim().toLowerCase().replaceAll("_","-").replace(/\s+/g," ");
const flatten=value=>{if(value===null||value===undefined)return[];if(Array.isArray(value))return value.flatMap(flatten);if(typeof value==="object")return Object.entries(value).flatMap(([key,item])=>[key,...flatten(item)]);return[String(value)]};
export function canonicalRegion(value){const raw=norm(value),state=STATE_CODES[raw];if(state)return state;const compact=String(value??"").trim().toUpperCase().replace(/[^A-Z0-9]/g,"");if(/^DE[1-9A-G][A-Z0-9]{0,2}$/.test(compact))return compact.slice(0,3);return null}
export function parseRegionRule(value){const values=flatten(value),regions=new Set();for(const item of values){const region=canonicalRegion(item);if(region)regions.add(region)}return {regions:[...regions].sort(),raw:value,condition:typeof value==="object"&&!Array.isArray(value)?value.condition||value.bedingung||null:null}}
export function resolveTenderRegions(tender,lots=[]){const structured=[...(tender.regions||[]),...lots.flatMap(lot=>flatten(lot.locations))],states=new Set(),nuts=new Set(),unknown=[];let nationwide=false;for(const item of structured){const compact=String(item??"").trim().toUpperCase().replace(/[^A-Z0-9]/g,"");if(["DEU","DE","ANYW","ANYWHERE"].includes(compact)){nationwide=true;continue}const state=canonicalRegion(item);if(state){states.add(state);if(/^DE[1-9A-G][A-Z0-9]{1,2}$/.test(compact))nuts.add(compact)}else if(String(item??"").trim())unknown.push(String(item))}const text=`${tender.title||""} ${tender.description||""}`.toLowerCase();if(/\b(bundesweit|deutschlandweit|gesamtes bundesgebiet|bundesgebiet)\b/.test(text))nationwide=true;return {states:[...states].sort(),stateLabels:[...states].sort().map(x=>STATE_LABELS[x]||x),nuts:[...nuts].sort(),nationwide,unknown,sourceData:{regions:tender.regions||[],lotLocations:lots.map(x=>({lotId:x.id||null,externalId:x.external_id||null,locations:x.locations||[]}))}}}

const intersection=(a,b)=>a.filter(x=>b.includes(x));
const applies=(rule,state)=>rule.regions.some(region=>region===state||state.startsWith(region)||region.startsWith(state));
export function classifyRegion({company,tender,lots=[],config={},applicable=true}){
 const resolved=resolveTenderRegions(tender,lots),a08=parseRegionRule(config.A08),a09=parseRegionRule(config.A09),a10=parseRegionRule(config.A10),b07=config.B07?parseRegionRule(config.B07):null;
 const base={companyId:company.company_id,company:company.legal_name,tenderId:tender.id,detectedStates:resolved.stateLabels,detectedStateCodes:resolved.states,nuts:resolved.nuts,sourceData:resolved.sourceData,configVersion:config.versionNo||null,configVersionId:config.versionId||null,ruleSnapshot:{A08:a08,A09:a09,A10:a10,B07:b07},matchingStatus:"REGION_GATE_PENDING",openConditions:[],parameterKey:null};
 const finish=(classification,decision,parameterKey,reason,nextAction,extra={})=>({...base,classification,label:REGION_LABELS[classification],decision,parameterKey,reason,nextAction,...extra});
 if(company.sector_status==="manual-sector-approval-required")return finish("REGION_UNRESOLVED","BOARD_DECISION_REQUIRED",null,"Gesonderte Sektorfreigabe für Sicherheitsdienstleistungen erforderlich.","Sektorfreigabe durchführen",{matchingStatus:"BLOCKED_BY_PERMISSION"});
 if(!applicable)return finish("NOT_APPLICABLE","NOT_APPLICABLE",null,"Der Leistungsbereich der Ausschreibung passt nicht zum bestätigten Gesellschaftsprofil.","Keine Regionsaktion erforderlich",{matchingStatus:"NOT_APPLICABLE"});
 if(!config.versionId||(!a08.regions.length&&!a09.regions.length&&!a10.regions.length))return finish("REGION_UNRESOLVED","CONFIGURATION_REQUIRED","A08","Regionsprofil dieser Gesellschaft noch nicht vollständig konfiguriert.","Regionskonfiguration öffnen",{matchingStatus:"REGION_REVIEW_REQUIRED"});
 if(resolved.nationwide&&resolved.states.length===0)return finish("MULTI_REGION_REVIEW","BOARD_DECISION_REQUIRED",null,"Bundesweites Leistungsgebiet ohne eindeutig zuordenbare Einzelabrufregionen.","Rahmenvertrag und Einzelabrufe prüfen",{matchingStatus:"REGION_REVIEW_REQUIRED"});
 if(resolved.states.length>1)return finish("MULTI_REGION_REVIEW","BOARD_DECISION_REQUIRED",null,`Mehrere Leistungsregionen erkannt: ${resolved.stateLabels.join(", ")}. Lose müssen einzeln geprüft werden.`,"Lose und Leistungsorte einzeln prüfen",{matchingStatus:"REGION_REVIEW_REQUIRED"});
 if(resolved.states.length===0)return finish("REGION_UNRESOLVED","REGION_REVIEW_REQUIRED",null,"Leistungsort, Bundesland oder NUTS-Region konnte aus den strukturierten Quelldaten nicht eindeutig bestimmt werden.","Quelldaten und Leistungsort prüfen",{matchingStatus:"REGION_REVIEW_REQUIRED"});
 const state=resolved.states[0],label=resolved.stateLabels[0];
 if(applies(a10,state))return finish("EXCLUDED_REGION","NO_GO_REGION","A10",`NO-GO Region: ${label} – durch A10 ausgeschlossen.`,"Ausschluss dokumentieren",{matchingStatus:"REGION_HARD_GATE_FAILED"});
 const conflicts=[...intersection(a08.regions,a09.regions),...intersection(a08.regions,a10.regions),...intersection(a09.regions,a10.regions)];
 if(conflicts.length)return finish("REGION_CONFIG_CONFLICT","BOARD_DECISION_REQUIRED",null,`Widersprüchliche Regionskonfiguration für ${[...new Set(conflicts)].map(x=>STATE_LABELS[x]||x).join(", ")}.`,"Regionskonfiguration korrigieren",{matchingStatus:"REGION_CONFIG_CONFLICT"});
 if(applies(a08,state))return finish("CORE_REGION","REGION_GATE_PASSED","A08",`Kernregion: ${label} – A08 erfüllt.`,"Weitere Mindestgates prüfen",{matchingStatus:"REGION_GATE_PASSED"});
 if(applies(a09,state))return finish("STRATEGIC_REGION","BOARD_DECISION_REQUIRED","A09",`Strategische Region: ${label} – Bedingung aus A09 ist vor einer positiven Empfehlung zu prüfen.`,"A09-Bedingung prüfen",{matchingStatus:"CONDITIONAL_REGION",openConditions:a09.condition?[String(a09.condition)]:["Strategische Bedingung ist nicht automatisch nachweisbar"]});
 return finish("OUTSIDE_CORE_REGION","BOARD_DECISION_REQUIRED","A08",`Außerhalb der Kernregion: ${label} ist weder in A08 noch in A09 enthalten.`,"Regionskonfiguration prüfen",{matchingStatus:"OUTSIDE_CORE_REGION"});
}

export function regionAllowsPreliminaryGo(evaluation,{otherMinimumGatesPassed=false,serviceApplicable=true}={}){return serviceApplicable&&otherMinimumGatesPassed&&evaluation.classification==="CORE_REGION"&&evaluation.decision==="REGION_GATE_PASSED"}
export function serviceApplicable(tender,profile){const cpv=profile?.capabilities?.cpvCodes||[],keywords=[...(profile?.capabilities?.keywords||[]),...(profile?.capabilities?.synonyms||[])].map(norm),haystack=norm(`${tender.title||""} ${tender.description||""}`),tenderCpv=tender.cpv_codes||[];if(!cpv.length&&!keywords.length)return null;return cpv.some(code=>tenderCpv.some(x=>String(x).startsWith(String(code))))||keywords.some(x=>x&&haystack.includes(x))}
