import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import {evaluateProfile,profileFieldDefinitions,profileFieldByKey,profileFingerprint,setProfileField} from "../platform/company-profile-completion.mjs";

const completeSource={sourceType:"BOARD_RESOLUTION",sourceLabel:"Beschluss",issuer:"Vorstand",verificationStatus:"VERIFIED",verifiedBy:"actor",verifiedAt:"2026-08-20T00:00:00Z"};
const base=()=>({id:"00000000-0000-4000-8000-000000000001",company_id:"00000000-0000-4000-8000-000000000002",version:2,capabilities:{registerCourt:"NOCH ZU PFLEGEN",commercialRegisterNumber:"NOCH ZU PFLEGEN",centralCompanyId:"NOCH ZU PFLEGEN",sector:"NOCH ZU PFLEGEN"},certifications:{permits:[],items:[]},reference_profile:{categories:[]},commercial_profile:{capacityLimits:"NOCH ZU PFLEGEN",minimumOrderValue:"NOCH ZU PFLEGEN",maximumOrderValue:"NOCH ZU PFLEGEN",preferredDurations:"NOCH ZU PFLEGEN",maximumDistance:"NOCH ZU PFLEGEN",subcontractorModels:"NOCH ZU PFLEGEN",targetMargins:"NOCH ZU PFLEGEN",riskLimits:"NOCH ZU PFLEGEN",approvedCostParameters:"NOCH ZU PFLEGEN"},field_provenance:{}});

test("every required company-profile field has a concrete action, area, role and allowed source",()=>{
  assert.equal(profileFieldDefinitions.length,16);
  for(const field of profileFieldDefinitions){assert.ok(field.action);assert.ok(field.area);assert.ok(field.role);assert.ok(field.source.label);assert.ok(field.source.types.length);assert.ok(field.target.length===2)}
});
test("missing value and source are distinguished",()=>{const result=evaluateProfile(base());assert.equal(result.fields.find(x=>x.key==="registerCourt").state,"VALUE_AND_SOURCE_MISSING");assert.equal(result.missingValues,16);assert.equal(result.releaseReady,false)});
test("a value without provenance remains blocked by missing source",()=>{const profile=setProfileField(base(),profileFieldByKey.registerCourt,"Berlin");assert.equal(evaluateProfile(profile).fields[0].state,"SOURCE_MISSING")});
test("a pending or disallowed source remains non-authoritative",()=>{const profile=setProfileField(base(),profileFieldByKey.riskLimits,"5 %");profile.field_provenance.riskLimits={...completeSource,sourceType:"RISK_RESOLUTION",verificationStatus:"PENDING_REVIEW"};assert.equal(evaluateProfile(profile).fields.find(x=>x.key==="riskLimits").state,"SOURCE_NOT_AUTHORITATIVE")});
test("source without a value remains a value blocker",()=>{const profile=base();profile.field_provenance.riskLimits={...completeSource,sourceType:"RISK_RESOLUTION"};assert.equal(evaluateProfile(profile).fields.find(x=>x.key==="riskLimits").state,"VALUE_MISSING")});
test("all values and field-compatible verified sources produce readiness but never approval",()=>{let profile=base();for(const field of profileFieldDefinitions){if(field.key==="subcontractorModels"){profile.field_provenance[field.key]={notApplicable:true,notApplicableReason:"Keine Nachunternehmer zugelassen",verifiedBy:"actor"};continue}profile=setProfileField(profile,field,["permits","certifications","references"].includes(field.key)?["belegt"]:"belegt");profile.field_provenance[field.key]={...completeSource,sourceType:field.source.types[0]}}const result=evaluateProfile(profile);assert.equal(result.completenessPercent,100);assert.equal(result.releaseReady,true);assert.equal(profile.approved_at,undefined)});
test("expired evidence remains a blocker",()=>{const profile=setProfileField(base(),profileFieldByKey.permits,["§34a"]);profile.field_provenance.permits={...completeSource,sourceType:"PERMIT_OR_CERTIFICATE",validUntil:"2020-01-01"};assert.equal(evaluateProfile(profile,new Date("2026-08-20T00:00:00Z")).fields.find(x=>x.key==="permits").state,"EVIDENCE_EXPIRED")});
test("not applicable requires the allowed field, reason and verifier",()=>{const profile=base();profile.field_provenance.subcontractorModels={notApplicable:true};assert.equal(evaluateProfile(profile).fields.find(x=>x.key==="subcontractorModels").state,"NOT_APPLICABLE_REASON_MISSING");profile.field_provenance.subcontractorModels.notApplicableReason="Keine Nachunternehmer zugelassen";profile.field_provenance.subcontractorModels.verifiedBy="actor";assert.equal(evaluateProfile(profile).fields.find(x=>x.key==="subcontractorModels").state,"COMPLETE")});
test("fingerprint changes with a field draft and is deterministic",()=>{const profile=base(),same=structuredClone(profile);assert.equal(profileFingerprint(profile),profileFingerprint(same));assert.notEqual(profileFingerprint(profile),profileFingerprint(setProfileField(profile,profileFieldByKey.maximumDistance,100)))});
test("UI renders current versions first, history, field actions, wizard, focus and mobile contract",()=>{const js=fs.readFileSync(new URL("../platform/assets/autopilot-navigation.js",import.meta.url),"utf8"),css=fs.readFileSync(new URL("../platform/assets/autopilot-navigation.css",import.meta.url),"utf8");for(const token of ["Pflichtfelder vervollständigen","data-profile-field","Versionshistorie anzeigen","Mit aktueller Version vergleichen","Als Entwurf speichern","Speichern und weiter","Später fortsetzen","textarea[name=value]"])assert.match(js,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(css,/@media\(max-width:700px\)/)});
test("route contract locks current version, company scope, optimistic hash, audit and no automatic approval",()=>{const route=fs.readFileSync(new URL("../platform/autopilot-routes.mjs",import.meta.url),"utf8");for(const token of ["historical_profile_immutable","company_scope_forbidden","profile_version_conflict","COMPANY_PROFILE_FIELD_DRAFT_SAVED","autoApproved:false","profile_evidence_malware"])assert.match(route,new RegExp(token))});
test("isolated evidence migration forces RLS and stores only profile-bound scanned evidence",()=>{const sql=fs.readFileSync(new URL("../migrations/102_company_profile_field_evidence.sql",import.meta.url),"utf8");assert.match(sql,/FORCE ROW LEVEL SECURITY/);assert.match(sql,/company_profile_id uuid NOT NULL/);assert.match(sql,/company_id uuid NOT NULL/);assert.match(sql,/sha256 text NOT NULL/);assert.match(sql,/malware_scan_status text NOT NULL/);assert.doesNotMatch(sql,/portal_credential|region_profile|management_inbox/)});
