import test from "node:test";
import assert from "node:assert/strict";
import {existsSync,readFileSync} from "node:fs";
import {createServer} from "node:http";
import {chromium} from "playwright";

const browserPath=process.env.CHROMIUM_EXECUTABLE_PATH||chromium.executablePath(),browserAvailable=existsSync(browserPath),ui=readFileSync(new URL("../platform/assets/autopilot-navigation.js",import.meta.url));
const tender="81111111-1111-4111-8111-111111111111",company="82222222-2222-4222-8222-222222222222",required="83333333-3333-4333-8333-333333333333",source="85555555-5555-4555-8555-555555555555",sha="b".repeat(64),mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document";

test("DOCX fields autosave as bound versions, reopen, and never call an external host",{skip:!browserAvailable},async t=>{
  let version=1,values={"docx:REQUIRED:company_name":"Alt GmbH","docx:company_type":"GmbH"},status="MISSING";const calls=[];
  const fields=()=>[{id:"docx:REQUIRED:company_name",label:"Firmenname",type:"text",required:true,value:values["docx:REQUIRED:company_name"],options:[],source:{part:"word/document.xml",index:1,tag:"REQUIRED:company_name"}},{id:"docx:company_type",label:"Rechtsform",type:"select",required:false,value:values["docx:company_type"],options:["GmbH","AG"],source:{part:"word/document.xml",index:2,tag:"company_type"}}];
  const server=createServer(async(req,res)=>{calls.push({method:req.method,url:req.url});
    if(req.method==="GET"&&req.url.startsWith("/admin/ausschreibungen/autopilot/management-output")){res.setHeader("content-type","text/html; charset=utf-8");res.setHeader("set-cookie","wb_csrf=office-token; Path=/; SameSite=Strict");return res.end('<!doctype html><body data-base="/admin/ausschreibungen" data-api="/api/tender"><nav id="autopilot-nav"></nav><section id="autopilot-content"></section><script src="/autopilot-navigation.js"></script></body>')}
    if(req.url==="/autopilot-navigation.js"){res.setHeader("content-type","application/javascript; charset=utf-8");return res.end(ui)}
    if(req.method==="GET"&&req.url.startsWith("/api/tender/final-preflight/contexts"))return json(res,{items:[{tender_id:tender,company_id:company,lot_key:"LOT-OFFICE",calculation_id:null,readiness_status:"OPEN",requirements:[]}]});
    if(req.method==="GET"&&req.url.startsWith(`/api/tender/tenders/${tender}/management-output`)){res.statusCode=404;return json(res,{error:"not_found"})}
    if(req.method==="GET"&&req.url.startsWith(`/api/tender/tenders/${tender}/required-documents?`))return json(res,{summary:{missing:status==="MISSING"?1:0,blockers:1,manualReview:status==="MANUAL_REVIEW_REQUIRED"?1:0,validated:0},items:[{id:required,requirement_title:"Strukturiertes Word-Preisformular",requirement_description:"Vom Bieter auszufüllen",source_reference:"Formblatt.docx",mandatory:true,submission_relevant:true,requirement_classification:"FILLABLE_BIDDER_FORM",classification_reason:"Exakt gebundene strukturierte Felder.",action_type:"OFFICE_EDITOR",satisfaction_status:status,status_label:status==="MISSING"?"Einzureichendes Dokument fehlt":"Dokument gespeichert – bereit zur fachlichen Prüfung",source_document:{available:true,documentId:source,sha256:sha,filename:"Formblatt.docx",documentVersion:1,mimeType:mime},original_form:{status:"PROVEN_EDITABLE_FORM",downloadable:true,editable:true,documentId:source,documentVersion:1,filename:"Formblatt.docx",mimeType:mime,sha256:sha}}]});
    if(req.method==="POST"&&req.url.endsWith(`/${required}/working-copy/office`)){const body=await request(req);assert.deepEqual(body.body,{company,lot:"LOT-OFFICE"});assert.equal(body.csrf,"office-token");return json(res,{item:{id:"copy",version},idempotent:version>1,editorType:"OFFICE",transmitted:false},version>1?200:201)}
    if(req.method==="GET"&&req.url.includes(`/${required}/working-copy/office/fields?`))return json(res,{item:{id:"copy",version,filename:"Arbeitskopie-Formblatt.docx",mediaType:mime,format:"DOCX",sha256:"a".repeat(64),sourceSha256:sha,fields:fields(),structuredFieldCount:2},editorType:"OFFICE",structuredPreview:true,visualReviewRequired:true,originalUnchanged:true,transmitted:false});
    if(req.method==="POST"&&req.url.endsWith(`/${required}/working-copy/office/fields`)){const body=await request(req);assert.equal(body.csrf,"office-token");assert.equal(body.body.baseVersion,version);values={...values,...body.body.fields};version++;status="MANUAL_REVIEW_REQUIRED";return json(res,{item:{id:"copy",version,filename:"Arbeitskopie-Formblatt.docx",media_type:mime,sha256:"a".repeat(64)},materiallyEdited:true,rereadVerified:true,visualReviewRequired:true,status,statusLabel:"Dokument gespeichert – bereit zur fachlichen Prüfung",externalWrite:false,transmitted:false},201)}
    if(req.method==="GET"&&req.url.includes(`/${required}/working-copy/office?`)){res.setHeader("content-type",mime);return res.end(Buffer.from("PK\u0003\u0004synthetic-docx"))}
    res.statusCode=404;return json(res,{error:"fixture_not_found",url:req.url});
  });
  await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));t.after(()=>server.close());const browser=await chromium.launch({headless:true,executablePath:browserPath});t.after(()=>browser.close());const page=await browser.newPage(),errors=[],cdp=await page.context().newCDPSession(page);await cdp.send("Runtime.enable");cdp.on("Runtime.exceptionThrown",event=>errors.push(JSON.stringify(event.exceptionDetails)));page.on("pageerror",error=>errors.push(error.stack||error.message));const origin=`http://127.0.0.1:${server.address().port}`;await page.goto(`${origin}/admin/ausschreibungen/autopilot/management-output?tender=${tender}&company=${company}&lot=LOT-OFFICE`,{waitUntil:"networkidle"});
  const edit=page.getByRole("button",{name:"Word am Bildschirm ausfüllen"});await edit.waitFor({timeout:5000}).catch(async error=>{throw new Error(`${await page.content()}\nCALLS=${JSON.stringify(calls)}\nERRORS=${errors.join(" | ")}\n${error.message}`)});await edit.click();await page.getByRole("heading",{name:"DOCX am Bildschirm ausfüllen"}).waitFor();const companyInput=page.locator('[data-office-field="docx:REQUIRED:company_name"]');await companyInput.fill("WB-Cleaning GmbH");await page.getByText("Version 2 gespeichert und vollständig wieder eingelesen",{exact:false}).waitFor({timeout:6000});assert.equal(values["docx:REQUIRED:company_name"],"WB-Cleaning GmbH");
  await page.locator('[data-office-field="docx:company_type"]').selectOption("AG");await page.getByRole("button",{name:"Jetzt versioniert speichern"}).click();await page.getByText("Version 3 gespeichert und vollständig wieder eingelesen",{exact:false}).waitFor();assert.equal(values["docx:company_type"],"AG");const downloaded=await page.locator("[data-office-download]").evaluate(async link=>{const response=await fetch(link.href,{credentials:"same-origin"}),bytes=new Uint8Array(await response.arrayBuffer());return {status:response.status,mime:response.headers.get("content-type"),magic:String.fromCharCode(...bytes.slice(0,2))}});assert.deepEqual(downloaded,{status:200,mime,magic:"PK"});
  await page.getByRole("button",{name:"Schließen"}).click();await page.getByRole("button",{name:"Word am Bildschirm ausfüllen"}).click();assert.equal(await page.locator('[data-office-field="docx:REQUIRED:company_name"]').inputValue(),"WB-Cleaning GmbH");assert.equal(await page.locator('[data-office-field="docx:company_type"]').inputValue(),"AG");assert.equal(await page.locator("[data-office-version]").textContent(),"3");
  assert.equal(calls.some(call=>/^https?:/i.test(call.url)),false);assert.equal(calls.filter(call=>call.method!=="GET").every(call=>call.url.startsWith("/api/tender/")),true);assert.deepEqual(errors,[]);
});

const json=(res,value,status=200)=>{res.statusCode=status;res.setHeader("content-type","application/json");res.end(JSON.stringify(value))},request=async req=>{let raw="";for await(const chunk of req)raw+=chunk;return {body:JSON.parse(raw),csrf:req.headers["x-csrf-token"]}};
